### ISSUE TITLE
Response for list api calls does not include the meta field

### ISSUE THREAD

**Issue by Josiah-J** [gray-adeyi/pypaystack2#5]
Paystack now returns a meta field with every list call.  Can that be included in the returned response?

**Comment by gray-adeyi** [comment]
Hi @Josiah-J ! it should still work the same. The `Response` object returned from calling any of the client methods is a named tuple. Here's a link to the documentation https://gray-adeyi.github.io/pypaystack2 you can also try out CLI https://pypi.org/project/paystack-cli/
Please let me know if you encounter any bugs

**Comment by gray-adeyi** [comment]
Oh I see now! @Josiah-J the current implementation won't capture that because it's not included as part data property. It would be included in the next release of this project. Does it really affect what you're working on or you have a workaround you can use in the meantime?

**Comment by gray-adeyi** [comment]
Hi @Josiah-J this feature has been added to `v2.1.0`. Happy coding 😎
